### PR TITLE
Fix gallery rendering - too many requests to blockchain

### LINKED ISSUE #238: Gallery page is making too may requests to the blockchain
We have to find a way for not making the current amount of requests that we are doing when rendering the Gallery Page, as it is doing around 100~ requests to infura, and that wouldn't scale to a production level.

### PR DESCRIPTION
**Pull request by mjlescano**
Closes #238 

This PR fixes the amount of requests to the blockchain by locally calculating if a given `tokenId` is already revealed instead of asking the contract.

### CODE REVIEW

File: packages/dapp/hooks/useGallery.js [hunk 1]
```diff
@@ -1,15 +1,12 @@
...
-
-import { zeroAccount } from '../constants/common';
-import { DEFAULT_NETWORKS_PER_ENVIRONMENT } from '../constants/networks';
-
 import getChainData from '../helpers/get-chain-data';
 import isSupportedNetwork from '../helpers/is-supported-network';
+import { ABI, CONTRACT_ADDRESS, CONTRACT_BLOCK } from '../config';
+import { DEFAULT_NETWORKS_PER_ENVIRONMENT } from '../constants/networks';
+import { WalletContext } from '../contexts/WalletProvider';
+import { zeroAccount } from '../constants/common';
```
Comment (mjlescano) [inline packages/dapp/hooks/useGallery.js:9]: Prettier being prettier.

File: packages/dapp/hooks/useGallery.js [hunk 2]
```diff
@@ -31,7 +28,7 @@ const useGallery = () => {
 
       const provider = new providers.JsonRpcProvider(rpcUrl);
 
-      const contract = new Contract(CONTRACT_ADDRESS, ABI, provider);
+      const Ethernauts = new Contract(CONTRACT_ADDRESS, ABI, provider);
```
Comment (mjlescano) [inline packages/dapp/hooks/useGallery.js:31]: Just changed the name from `contract` to `Ethernauts` to be consistent with the backend.

File: packages/dapp/hooks/useGallery.js [hunk 3]
```diff
@@ -41,39 +38,44 @@ const useGallery = () => {
         toBlock: 'latest',
       };
 
-      const logs = await provider.getLogs(filter);
+      const [batchSize, totalSupply] = await Promise.all([
+        Ethernauts.batchSize().then(Number),
+        Ethernauts.totalSupply().then(Number),
+      ]);
```
Comment (mjlescano) [inline packages/dapp/hooks/useGallery.js:44]: Here, instead of asking the contract for each token, we just get the amount of tokens are minted and the batch size, and then with that we can calculate if any token is revealed by its ID.

File: packages/dapp/hooks/useGallery.js [hunk 4]
```diff
@@ -41,39 +38,44 @@ const useGallery = () => {
...
-        }
+            isRevealed: tokenId <= maxTokenIdRevealed,
+          };
 
-        // Push all nfts
-        if (from === zeroAccount.toLowerCase()) {
-          resolvedAcumm.allGalleryItems.push({
-            tokenId,
-            owner: to,
-            isRevealed: await contract.isTokenRevealed(tokenId),
```
Comment (mjlescano) [inline packages/dapp/hooks/useGallery.js:71]: This was the culprit, we were doing this request for each token ☝️

**Review by saeta-eth — APPROVED** [review]
Looks good Mati!
